services:

  adk:
    container_name: idea-agent-adk
    restart: no
    build:
      context: ./build
      dockerfile: Dockerfile.adk
    ports:
      - "8000:8000"
    volumes:
      - ./app/adk:/app
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json

  #mcp:
  #  container_name: idea-agent-mcp
  #  restart: no
  #  build:
  #    context: ./build
  #    dockerfile: Dockerfile.mcp
  #  depends_on:
  #    - neo4j
  #  ports:
  #    - "8001:8001"
  #  volumes:
  #    - ./app/mcp:/app
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - NEO4J_URI=bolt://neo4j:7687
  #    - NEO4J_USER=neo4j
  #    - NEO4J_PASSWORD=password

  neo4j:
    container_name: idea-agent-neo4j
    restart: no
    image: neo4j:2025.10.1
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./app/neo4j/data:/data
      - ./app/neo4j/logs:/logs
      - ./app/neo4j/import:/import
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      # APOC
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true

  fma:
    container_name: idea-agent-fma
    restart: no
    build:
      context: ./build
      dockerfile: Dockerfile.fma
    ports:
      - "8002:8002"
    volumes:
      - ./app/fma:/app/app
      - ./logs:/logs
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - ENV=development
    # Überschreibt den CMD aus dem Dockerfile für Hot-Reloading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    depends_on:
      - neo4j

networks:
  idea-agent-network:
    driver: bridge