CREATE
(gn1:Composition:CoinReverse {composition_id: 1, slug: "reverse"})<-[:HAS_COMPOSITION]-(gn2:Unit:Coin {unit_id: 2, slug: "cn-11396", src_url: "https://www.corpus-nummorum.eu/CN_11396", nomisma_mint: "bizya", nomisma_material: "ae", nomisma_denomination: "oneandahalf-unit", year_min: 138, year_max: 161})-[:HAS_COMPOSITION]->(gn3:Composition:CoinObverse {composition_id: 3, slug: "obverse"})-[:HAS_COMPOSITION_ENTITY]->(gn4:CompositionEntity {composition_entity_id: 4, slug: "figure"})-[:HAS_INTERPRETATION]->(gn5:Interpretation {interpretation_id: 5, slug: "zeus", certainty: 0.5, reasoning_statement: "The complementary use of Zeus on the reverse suggests that the figure on the obverse should also be interpreted as Zeus.", timestamp: "2026-02-18", status: "Alternative"})-[:IDENTIFIED_AS]->(gn6:Concept:Entity {concept_id: 6, slug: "zeus"})-[:IS_A]->(gn7:Concept:Entity {concept_id: 7, slug: "deity"})<-[:IS_A]-(gn8:Concept:Entity {concept_id: 8, slug: "poseidon"}),
(gn9:Agent:HumanAgent {agent_id: 9, slug: "researcher"})<-[:STATED_BY]-(gn10:Interpretation {interpretation_id: 10, slug: "poseidon", certainty: 0.4, reasoning_statement: "This form of depiction is documented for Poseidon, but not for this mint.", timestamp: "2026-02-18", status: "Alternative"})-[:SUPPORTED_BY]->(gn11:Architectonic:Methodology {architectonic_id: 11, slug: "common-scheme"})-[:IS_A]->(gn12:Architectonic:Methodology {architectonic_id: 12, slug: "supporting-observation"})<-[:IS_A]-(gn13:Architectonic:Methodology {architectonic_id: 13, slug: "complementarity"})<-[:SUPPORTED_BY]-(gn5)-[:IMPAIRED_BY]->(gn14:Architectonic:Methodology {architectonic_id: 14, slug: "missing-attributes"})-[:IS_A]->(gn15:Architectonic:Methodology {architectonic_id: 15, slug: "source-of-uncertainty"})<-[:IS_A]-(gn16:Architectonic:Methodology {architectonic_id: 16, slug: "no-local-tradition"}),
(gn9)<-[:STATED_BY]-(gn5)-[:HAS_SOURCE_REFERENCE]->(gn17:SourceReference {source_reference_id: 17, slug: "z-tachev-2019", reference_statement: "Tachev stated Zeus, no reasoning", reference: "P. 180-181, nr. 4, pl. 1"})-[:HAS_SOURCE]->(gn18:Source {source_id: 18, slug: "tachev-2019", source_id: 18, slug: "tachev-2019"})<-[:HAS_SOURCE]-(gn19:SourceReference {source_reference_id: 19, slug: "p-tachev-2019", reference_statement: "Tachev stated Zeus, no reasoning", reference: "P. 180-181, nr. 4, pl. 1"})-[:HAS_EVIDENTIARY_RELATIONSHIP]->(gn20:Architectonic:Methodology {architectonic_id: 20, slug: "conflicting"}),
(gn7)-[:IS_A]->(gn21:Concept:Entity {concept_id: 21, slug: "figure"})<-[:IDENTIFIED_AS]-(gn22:Interpretation {interpretation_id: 22, slug: "figure", certainty: 1.0, reasoning_statement: "Morphologically human, but could be a deity", timestamp: "2026-02-18", status: "Primary"})<-[:HAS_INTERPRETATION]-(gn4)-[:HAS_INTERPRETATION]->(gn10)-[:IDENTIFIED_AS]->(gn8),
(gn23:CompositionFeature {composition_feature_id: 23, slug: "bearded"})<-[:HAS_COMPOSITION_FEATURE]-(gn4)-[:HAS_COMPOSITION_FEATURE]->(gn24:CompositionFeature {composition_feature_id: 24, slug: "portrait"})-[:HAS_INTERPRETATION]->(gn25:Interpretation {interpretation_id: 25, slug: "portrait", certainty: 1.0, reasoning_statement: "Clear visual truncation, shoulder line", timestamp: "2026-02-18", status: "Primary"})-[:IDENTIFIED_AS]->(gn26:Concept:Feature {concept_id: 26, slug: "portrait"})-[:IS_A]->(gn27:Concept:Feature {concept_id: 27, slug: "visual-scope"}),
(gn5)-[:HAS_SOURCE_REFERENCE]->(gn28:SourceReference {source_reference_id: 28, slug: "z-jurukova-1981", reference_statement: "Jurukova stated Poseidon, no reasoning", reference: "P. 79, nr. 170, pl. 28, fig. 170"})-[:HAS_SOURCE]->(gn29:Source {source_id: 29, slug: "jurukova-1981", source_id: 29, slug: "jurukova-1981"})<-[:HAS_SOURCE]-(gn30:SourceReference {source_reference_id: 30, slug: "p-jurukova-1981", reference_statement: "Jurukova stated Poseidon, no reasoning", reference: "P. 79, nr. 170, pl. 28, fig. 170"})-[:HAS_EVIDENTIARY_RELATIONSHIP]->(gn31:Architectonic:Methodology {architectonic_id: 31, slug: "concurring"}),
(gn23)-[:HAS_INTERPRETATION]->(gn32:Interpretation {interpretation_id: 32, slug: "bearded", certainty: 1.0, reasoning_statement: "A beard is clearly observable", timestamp: "2026-02-18", status: "Primary"})-[:IDENTIFIED_AS]->(gn33:Concept:Feature {concept_id: 33, slug: "bearded"}),
(gn4)-[:HAS_COMPOSITION_FEATURE]->(gn34:CompositionFeature {composition_feature_id: 34, slug: "male"})-[:HAS_INTERPRETATION]->(gn35:Interpretation {interpretation_id: 35, slug: "male", certainty: 1.0, reasoning_statement: "Typical male attribute (beard)", timestamp: "2026-02-18", status: "Primary"})-[:IDENTIFIED_AS]->(gn36:Concept:Feature {concept_id: 36, slug: "male"}),
(gn17)-[:HAS_EVIDENTIARY_RELATIONSHIP]->(gn31)-[:IS_A]->(gn37:Architectonic:Methodology {architectonic_id: 37, slug: "evidentiary-relationship"})<-[:IS_A]-(gn20),
(gn28)-[:HAS_EVIDENTIARY_RELATIONSHIP]->(gn20),
(gn30)<-[:HAS_SOURCE_REFERENCE]-(gn10)-[:HAS_SOURCE_REFERENCE]->(gn19),
(gn16)<-[:IMPAIRED_BY]-(gn10)-[:IMPAIRED_BY]->(gn14),
(gn3)-[:HAS_IMAGE]->(gn38:Image {img_id: 38, slug: "11396-obverse", src_url: "https://data.corpus-nummorum.eu/storage/coins/11396/img/12963/o/thumbnails/lg.jpeg"});